apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-2

managedNodeGroups:
  - name: expense
    instanceTypes: ["m5.large"]
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    spot: false